version: '3.4'

services:
  ratelimitdemoapi:
    image: ratelimitdemoapi
    build:
      context: .
      dockerfile: RateLimitDemoApi/Dockerfile
    ports:
      - 5001:80
    depends_on:
      - redis     
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - RedisConnection_Host=redis
      - RedisConnection_Port=6379
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  redis:
      image: redis:alpine
      ports:
        - "6379:6379"